### PR TITLE
Config form in html file with variables

### PR DESCRIPTION
**Pull request by huelvayork**
- config form moved to an independent .html file. You can add personalized variables in the file. (see configform.html for an example)
- countdown to stop init (just send a tmr.stop(0))

if you connect a pushbutton between GPIO0 and ground, you may:
- set GPIO0 to ground (push button) to force init to run run_config even when config.lc exists
- set GPIO0 to ground (push button) while in config mode to restart

### CODE REVIEW

**Comment by timoline** [comment]
Great improvement thx.
But is it working stable for you?
8 out of 10 the AP webpage wont load

Also Password is not decoded/unescaped, ( see pull request 1, https://github.com/sebastianhodapp/ESPbootloader/pull/1)

**Comment by huelvayork** [comment]
Was working stable at home, where there is only one ssid in range, but today I tested at work, with a few aps available and it failed. Probably a memory problem. I'll try processing the html line by line.

**Comment by huelvayork** [comment]
confirmed: its a memory problem. I'm refactoring the source to use global variables instead of passing parameters to functions, and limiting the number of APs in the combo (if your ssid is not in the list you can type its name in the "hidden ssid" field)

**Comment by timoline** [comment]
Hello, thx for confirming.

Please have a look at this code I found and placed on github:https://github.com/timoline/ESPDraco
Code has the same goal with more code and with less memory usage.....,but with another approach.
It doesn't save sidd and password to a file, but it remembers it and autoconnect to it...

Maybe we can mix and merge some code for a perfect simple bootloader

**Comment by timoline** [comment]
thx,
Looks-like its working correct now but only when you compile the file run_config.lua, 
One small thing, the var aps in the configform.html isnt correct anymore and should be changed to available_aps

**Comment by huelvayork** [comment]
Thanks. I forgot to commit the html file changes. Will do it this afternoon.

**Pull request merged**
